### PR TITLE
a common fix plz merge

### PR DESCRIPTION
**Pull request by treatmeniceplz**
line 44 expains it all

### CODE REVIEW

**Comment by khaneliman** [comment]
This change is something that I thought of while testing out the install, as well. Glad someone else thought it needed addressing too. If the goal is to make the install as easy as possible and entering an invalid disk is so brutal as to reboot your system... the disk selection should be more clear.

**Comment by treatmeniceplz** [comment]
This was the whole point of the change!!!!!!!!!!!!

**Comment by khaneliman** [comment]
I had a look at the test branch and it looks like it has a better user experience with the new startup.sh, should take a look at that branch.

**Comment by treatmeniceplz** [comment]
Please elaborate

**Comment by treatmeniceplz** [comment]
> I had a look at the test branch and it looks like it has a better user experience with the new startup.sh, should take a look at that branch.

Elaborate on this

**Comment by khaneliman** [comment]
https://github.com/ChrisTitusTech/ArchTitus/blob/test/startup.sh#L94 they added a startup.sh file that changed all the options to be answered on launch of the script. This script has all new prompts for configuration options, one of which is an improved disk selection that shows a tree structure of your block devices.

**Comment by treatmeniceplz** [comment]
I will look in the morning

**Comment by ChrisTitusTech** [comment]
Approaching this differently on the test branch

**Pull request closed without merging**
