### PR TITLE
Remove Picom, Pulse and add Pipewire

### PR DESCRIPTION
**Pull request by kassindornelles**
It only causes harm (huge perfomance issues) in desktop environments like KDE Plasma and GNOME, both have their own compositors so better removed it from the list

### CODE REVIEW

**Comment by kassindornelles** [comment]
Would be better to install Picom per-DE if you wish, it would make sense in XFCE4 if you also made a config to disable the XFWM built-in compositor by default, the same on KDE (KWIN), running two compositors at the same time will completely obliterate performance

**Comment by kassindornelles** [comment]
Also another tip would be to include a option to select the GPU brand you use, for AMD for example you need to use the vulkan-radeon package instead of AMDVLK, vulkan-radeon (and lib32-vulkan-radeon) is the driver supported by Valve for AMD GPU's, AMDVLK is the official AMD driver that is super slower and lacks important Vulkan extensions for DXVK and VKD3D-Proton.

**Comment by kassindornelles** [comment]
Update: Also added Pipewire and Wireplumber to the PR

**Comment by ChrisTitusTech** [comment]
Agreed about picom had major performance issue with it a while back

**Pull request closed without merging**
