### PR TITLE
Update archtitus.sh

### PR DESCRIPTION
**Pull request by ashcode028**
the command for chrooting in is now artix-chroot

### CODE REVIEW

**Comment by mfgbhatti** [comment]
That is not for arch linux

**Review by khaneliman — CHANGES_REQUESTED** [review]
No.

**Comment by Xmetalfanx** [comment]
had to look this up ... that is for an entirely different distro ... BASED on arch  but NOT arch

**Comment by yehonatan2020** [comment]
zsh: command not found: artix-chroot

**Comment by ChrisTitusTech** [comment]
lol closing this non-sense

**Pull request closed without merging**
