### PR TITLE
Add xfce4 and lightdm install

### PR DESCRIPTION
**Pull request by ThePilotBoi**
test. i might actually just fork it

### CODE REVIEW

**Comment by ThePilotBoi** [comment]
dont use this i forgot xorg

**Comment by khaneliman** [comment]
This is one of those things that I think would be nice to create a startup option for choosing the desktop environment you'd like to use and install whichever one the user chooses.

**Comment by stojshic** [comment]
> This is one of those things that I think would be nice to create a startup option for choosing the desktop environment you'd like to use and install whichever one the user chooses.

I actually have this in my personal repo that I use for testing. It's not yet finished, but it works. It does need more work, as I only barely tested it, but I tried with adding cinnamon and gnome, and it installed fine. Still need reviewing the code some more, and making it more error proof tho

**Comment by ThePilotBoi** [comment]
> > This is one of those things that I think would be nice to create a startup option for choosing the desktop environment you'd like to use and install whichever one the user chooses.
> 
> I actually have this in my personal repo that I use for testing. It's not yet finished, but it works. It does need more work, as I only barely tested it, but I tried with adding cinnamon and gnome, and it installed fine. Still need reviewing the code some more, and making it more error proof tho

seems pretty cool!

**Review by troyBORG — APPROVED** [review]

**Comment by ChrisTitusTech** [comment]
Will implement this on the main branch at some point but I want to keep the server branch for server.

**Pull request closed without merging**
