### PR TITLE
Selectable input

### PR DESCRIPTION
**Pull request by khaneliman**
This is an alternative to https://github.com/ChrisTitusTech/ArchTitus/pull/182... The other PR continues the current method of manually typing in the option and us passing it along through installer. In PR 182 I just make sure they entered a number from the list. In this one I provide an interactive list they use num keys to select and enter to confirm their choice. 

Disk Selection: 
image

Filesystem
image

Timezone
image

Keymap
image

### CODE REVIEW

**Comment by vic1707** [comment]
Love it!

**Comment by stojshic** [comment]
I used your idea, which I really liked, and this is what I got...

Choosing a DE
Screenshot_arch_2022-01-17_20:20:33

Choosing a AUR helper
Screenshot_arch_2022-01-17_20:20:53

And also, I think config like this would be easily understandable for everyone. It's prefilled with needed packages, and user could add packages that he wants..
2022-01-17-203808_3840x1080_scrot

**Comment by khaneliman** [comment]
That looks great! I like the idea of separating the pkg-files out to be more modular like that so it's easier to maintain the packages per operation.

**Comment by vic1707** [comment]
Something that would help New commers could be to create subfolders like for the desktop the apps installed etc... 🤔

**Comment by pog5** [comment]
This is great! I tried it out and it works like a charm.

**Comment by stojshic** [comment]
Hey. Last few hours I've been working on Full/Minimal installations of DE. Do you think that would be good idea? I'm using the same input TXT file, with a row --END OF MINIMAL INSTALL--, and it should install packages after that only if user chooses FULL installation in the option. If he chooses MINIMAL, it will only install packages until that line. So, if someone wants pure DE, only bare minimum apps, it installs that, and if he wants all the apps and themes, then it install all the files until the end of file. If any of you guys have idea about what apps are minimal/full, please write to me so that I can populate the files. Thanks

**Comment by khaneliman** [comment]
@stojshic can you move that to the issue about minimal installation ?

**Review by Code-Ac — COMMENTED** [review]
LGTM, except the little detail that you can’t type in a custom keyboard layout anymore. For example I need de-latin1 instead of just de for my Laptop keyboard. Maybe an „Other“ option which then lets you type one in?

**Pull request merged**
